# Quantitative Value Strategy
"Value investing" means investing in the stocks that are cheapest relative to common measures of business value (like earnings or assets).

For this project, we're going to build an investing strategy that selects the 50 stocks with the best value metrics. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.

## Library Imports
The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [1]:
import numpy as np
import pandas as pd
import xlsxwriter # save file as an Excel file
import requests
from scipy import stats
import math

## Importing Our List of Stocks & API Token
As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the .csv file is still in your working directory and import it with the following command:

In [2]:
stocks = pd.read_csv("sp_500_stocks.csv")

from secrets import IEX_CLOUD_API_TOKEN

## Making Our First API Call
It's now time to make the first version of our value screener!

We'll start by building a simple value screener that ranks securities based on a single metric (the price-to-earnings ratio).

In [3]:
symbol = 'aapl'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/quote?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()
data

{'avgTotalVolume': 90680162,
 'calculationPrice': 'iexlasttrade',
 'change': -2.8,
 'changePercent': -0.01838,
 'close': 0,
 'closeSource': 'ialofcfi',
 'closeTime': None,
 'companyName': 'Apple Inc',
 'currency': 'USD',
 'delayedPrice': None,
 'delayedPriceTime': None,
 'extendedChange': None,
 'extendedChangePercent': None,
 'extendedPrice': None,
 'extendedPriceTime': None,
 'high': 0,
 'highSource': None,
 'highTime': None,
 'iexAskPrice': 0,
 'iexAskSize': 0,
 'iexBidPrice': 0,
 'iexBidSize': 0,
 'iexClose': 151.69,
 'iexCloseTime': 1722040505776,
 'iexLastUpdated': 1707926936052,
 'iexMarketPercent': 0.02601885235091976,
 'iexOpen': 157.4,
 'iexOpenTime': 1708669926906,
 'iexRealtimePrice': 156.12,
 'iexRealtimeSize': 203,
 'iexVolume': 2048052,
 'lastTradeTime': 1740319045435,
 'latestPrice': 155.04,
 'latestSource': 'IEX Last Trade',
 'latestTime': 'November 1, 2022',
 'latestUpdate': 1678254691191,
 'latestVolume': None,
 'low': 0,
 'lowSource': None,
 'lowTime': None,
 'marketCap': 2445491581667,
 'oddLotDelayedPrice': None,
 'oddLotDelayedPriceTime': None,
 'open': 0,
 'openTime': None,
 'openSource': 'ailoifcf',
 'peRatio': 24.7,
 'previousClose': 156.39,
 'previousVolume': 100976904,
 'primaryExchange': 'ADQNAS',
 'symbol': 'AAPL',
 'volume': None,
 'week52High': 183.9,
 'week52Low': 130.59,
 'ytdChange': -0.15224934992755,
 'isUSMarketOpen': False}

## Parsing Our API Call
This API call has the metric we need - the price-to-earnings ratio.

Here is an example of how to parse the metric from our API call:

In [4]:
price = data['latestPrice']
pe_ratio = data['peRatio']

## Executing A Batch API Call & Building Our DataFrame

Just like in our first project, it's now time to execute several batch API calls and add the information we need to our DataFrame.

We'll start by running the following code cell, which contains some code we already built last time that we can re-use for this project. More specifically, it contains a function called chunks that we can use to divide our list of securities into groups of 100.

In [5]:
# Function sourced from 
# https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'Price-to-Earnings Ratio', 'Number of Shares to Buy']

Now we need to create a blank DataFrame and add our data to the data frame one-by-one.

In [6]:
final_dataframe = pd.DataFrame(columns=my_columns)

for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/v1/stock/market/batch?symbols={symbol_string}&types=quote&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        if (symbol == 'DISCA' or symbol == 'HFC' or symbol == 'VIAC' or symbol == 'WLTW'): continue
        else: final_dataframe = final_dataframe.append(
            pd.Series(
                [
                    symbol,
                    data[symbol]['quote']['latestPrice'],
                    data[symbol]['quote']['peRatio'],
                    'N/A'
                ],
                index = my_columns
            ),
                ignore_index=True
        )
final_dataframe

    Ticker    Price Price-to-Earnings Ratio Number of Shares to Buy
0        A  147.670                    32.6                     N/A
1      AAL   14.274                   -6.04                     N/A
2      AAP  198.280                   22.54                     N/A
3     AAPL  154.730                   25.75                     N/A
4     ABBV  153.740                   21.35                     N/A
..     ...      ...                     ...                     ...
496    YUM  122.420                   24.07                     N/A
497    ZBH  113.270                  104.47                     N/A
498   ZBRA  243.900                   26.48                     N/A
499   ZION   52.882                     5.9                     N/A
500    ZTS  156.470                   35.54                     N/A

[501 rows x 4 columns]

## Removing Glamour Stocks

The opposite of a "value stock" is a "glamour stock". 

Since the goal of this strategy is to identify the 50 best value stocks from our universe, our next step is to remove glamour stocks from the DataFrame.

We'll sort the DataFrame by the stocks' price-to-earnings ratio, and drop all stocks outside the top 50.

In [7]:
final_dataframe.sort_values('Price-to-Earnings Ratio', inplace=True)
final_dataframe = final_dataframe[final_dataframe['Price-to-Earnings Ratio']>0]
final_dataframe = final_dataframe[:50]
final_dataframe.reset_index(inplace=True)
final_dataframe.drop('index',axis=1,inplace=True)
final_dataframe

   Ticker    Price Price-to-Earnings Ratio Number of Shares to Buy
0     NRG   44.300                     3.2                     N/A
1     AIG   58.780                    3.84                     N/A
2     PVH   54.810                    4.05                     N/A
3     PHM   39.900                     4.1                     N/A
4     NUE  137.000                    4.28                     N/A
5    DISH   15.286                    4.65                     N/A
6     COF  107.590                    4.73                     N/A
7     HPQ   28.420                    4.96                     N/A
8     DHI   80.490                    5.07                     N/A
9     AIV    8.300                    5.16                     N/A
10    MGM   36.870                     5.2                     N/A
11    HPE   14.800                    5.25                     N/A
12    LEN   84.600                     5.5                     N/A
13    APA   47.540                    5.52                     N/A
14    PFG   88.800                    5.53                     N/A
15     CE   99.170                     5.6                     N/A
16    VLO  134.000                    5.63                     N/A
17    KSS   30.120                    5.64                     N/A
18    SYF   36.700                    5.73                     N/A
19   ZION   52.882                     5.9                     N/A
20    HBI    7.200                    5.98                     N/A
21      C   47.770                     6.1                     N/A
22      F   13.600                    6.13                     N/A
23    LYB   78.500                    6.29                     N/A
24    TSN   71.000                     6.3                     N/A
25    DOW   47.210                    6.33                     N/A
26     WU   13.990                    6.39                     N/A
27    MOS   55.560                    6.43                     N/A
28     IP   34.880                    6.49                     N/A
29    AIZ  139.300                     6.7                     N/A
30    BEN   22.700                    6.73                     N/A
31    DFS  104.660                    6.85                     N/A
32     GM   40.530                     6.9                     N/A
33    IVZ   16.330                    6.92                     N/A
34      T   18.380                    7.02                     N/A
35    OXY   75.900                    7.27                     N/A
36    WBA   37.351                    7.34                     N/A
37     MU   57.380                    7.35                     N/A
38    MRO   31.950                    7.56                     N/A
39   FANG  160.280                     7.6                     N/A
40    WDC   36.400                    7.67                     N/A
41    KEY   18.930                    8.04                     N/A
42     GS  366.000                    8.25                     N/A
43     VZ   37.400                    8.28                     N/A
44    UNM   46.300                    8.76                     N/A
45   SIVB  237.830                    8.86                     N/A
46    SWK   80.010                    8.87                     N/A
47    MPC  122.600                    8.98                     N/A
48    DVA   72.500                    9.04                     N/A
49    EMN   79.780                    9.06                     N/A

## Calculating the Number of Shares to Buy
We now need to calculate the number of shares we need to buy. 

To do this, we will use the `portfolio_input` function that we created in our momentum project.

I have included this function below.

In [8]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input("Enter the value of your portfolio:")

    try:
        val = float(portfolio_size)
    except ValueError:
        print("That's not a number! \n Try again:")
        portfolio_size = input("Enter the value of your portfolio:")

Use the `portfolio_input` function to accept a `portfolio_size` variable from the user of this script.

In [10]:
portfolio_input()

Enter the value of your portfolio:1000000

You can now use the global `portfolio_size` variable to calculate the number of shares that our strategy should purchase.

In [13]:
position_size = float(portfolio_size)/len(final_dataframe.index)
for row in final_dataframe.index:
    final_dataframe.loc[row, 'Number of Shares to Buy'] = math.floor(position_size/final_dataframe.loc[row, 'Price'])
    
final_dataframe

   Ticker    Price Price-to-Earnings Ratio Number of Shares to Buy
0     NRG   44.300                     3.2                     451
1     AIG   58.780                    3.84                     340
2     PVH   54.810                    4.05                     364
3     PHM   39.900                     4.1                     501
4     NUE  137.000                    4.28                     145
5    DISH   15.286                    4.65                    1308
6     COF  107.590                    4.73                     185
7     HPQ   28.420                    4.96                     703
8     DHI   80.490                    5.07                     248
9     AIV    8.300                    5.16                    2409
10    MGM   36.870                     5.2                     542
11    HPE   14.800                    5.25                    1351
12    LEN   84.600                     5.5                     236
13    APA   47.540                    5.52                     420
14    PFG   88.800                    5.53                     225
15     CE   99.170                     5.6                     201
16    VLO  134.000                    5.63                     149
17    KSS   30.120                    5.64                     664
18    SYF   36.700                    5.73                     544
19   ZION   52.882                     5.9                     378
20    HBI    7.200                    5.98                    2777
21      C   47.770                     6.1                     418
22      F   13.600                    6.13                    1470
23    LYB   78.500                    6.29                     254
24    TSN   71.000                     6.3                     281
25    DOW   47.210                    6.33                     423
26     WU   13.990                    6.39                    1429
27    MOS   55.560                    6.43                     359
28     IP   34.880                    6.49                     573
29    AIZ  139.300                     6.7                     143
30    BEN   22.700                    6.73                     881
31    DFS  104.660                    6.85                     191
32     GM   40.530                     6.9                     493
33    IVZ   16.330                    6.92                    1224
34      T   18.380                    7.02                    1088
35    OXY   75.900                    7.27                     263
36    WBA   37.351                    7.34                     535
37     MU   57.380                    7.35                     348
38    MRO   31.950                    7.56                     625
39   FANG  160.280                     7.6                     124
40    WDC   36.400                    7.67                     549
41    KEY   18.930                    8.04                    1056
42     GS  366.000                    8.25                      54
43     VZ   37.400                    8.28                     534
44    UNM   46.300                    8.76                     431
45   SIVB  237.830                    8.86                      84
46    SWK   80.010                    8.87                     249
47    MPC  122.600                    8.98                     163
48    DVA   72.500                    9.04                     275
49    EMN   79.780                    9.06                     250

## Building a Better (and More Realistic) Value Strategy
Every valuation metric has certain flaws.

For example, the price-to-earnings ratio doesn't work well with stocks with negative earnings.

Similarly, stocks that buyback their own shares are difficult to value using the price-to-book ratio.

Investors typically use a `composite` basket of valuation metrics to build robust quantitative value strategies. In this section, we will filter for stocks with the lowest percentiles on the following metrics:

* Price-to-earnings ratio
* Price-to-book ratio
* Price-to-sales ratio
* Enterprise Value divided by Earnings Before Interest, Taxes, Depreciation, and Amortization (EV/EBITDA)
* Enterprise Value divided by Gross Profit (EV/GP)

Some of these metrics aren't provided directly by the IEX Cloud API, and must be computed after pulling raw data. We'll start by calculating each data point from scratch.

Let's move on to building our DataFrame. You'll notice that I use the abbreviation `rv` often. It stands for `robust value`, which is what we'll call this sophisticated strategy moving forward.

## Dealing With Missing Data in Our DataFrame

Our DataFrame contains some missing data because all of the metrics we require are not available through the API we're using. 

You can use pandas' `isnull` method to identify missing data:

Dealing with missing data is an important topic in data science.

There are two main approaches:

* Drop missing data from the data set (pandas' `dropna` method is useful here)
* Replace missing data with a new value (pandas' `fillna` method is useful here)

In this tutorial, we will replace missing data with the average non-`NaN` data point from that column. 

Here is the code to do this:

Now, if we run the statement from earlier to print rows that contain missing data, nothing should be returned:

## Calculating Value Percentiles

We now need to calculate value score percentiles for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* Price-to-earnings ratio
* Price-to-book ratio
* Price-to-sales ratio
* EV/EBITDA
* EV/GP

Here's how we'll do this:

## Calculating the RV Score
We'll now calculate our RV Score (which stands for Robust Value), which is the value score that we'll use to filter for stocks in this investing strategy.

The RV Score will be the arithmetic mean of the 4 percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the mean function from Python's built-in statistics module.

## Selecting the 50 Best Value StocksÂ¶

As before, we can identify the 50 best value stocks in our universe by sorting the DataFrame on the RV Score column and dropping all but the top 50 entries.

## Calculating the Number of Shares to Buy
We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a for loop to calculate the number of shares to buy for each stock in our investment universe.

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

## Creating the Formats We'll Need For Our .xlsx File
You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase
* Float formats with 1 decimal for each valuation metric

Since we already built some formats in past sections of this course, I've included them below for you. Run this code cell before proceeding.

## Saving Our Excel Output
As before, saving our Excel output is very easy: